"""Additive memory-v2 primitives for ControlMesh."""

from controlmesh.memory.capture import (
    capture_event,
    capture_event_batch,
    capture_evidence,
    capture_open_candidate,
    capture_signal,
    capture_signal_batch,
    expand_daily_note_skeleton,
)
from controlmesh.memory.commands import (
    apply_daily_note_promotions,
    apply_memory_dreaming_sweep,
    preview_daily_note_promotions,
    preview_memory_dreaming_sweep,
    search_memory,
    sync_memory_search,
)
from controlmesh.memory.dreaming import (
    acquire_dream_lock,
    apply_dreaming_sweep,
    load_checkpoints,
    load_sweep_state,
    preview_dreaming_sweep,
    release_dream_lock,
    save_checkpoints,
    save_sweep_state,
)
from controlmesh.memory.events import (
    AskParentEvent,
    EvidenceRef,
    EvidenceRefKind,
    MemoryEvent,
    MemoryEventKind,
    ResumeEvent,
    RoutingContext,
    SignalCandidate,
    SignalConfidence,
)
from controlmesh.memory.frequency import (
    PatternAnalysisResult,
    RepeatedPattern,
    find_repeated_patterns,
    render_patterns_summary,
)
from controlmesh.memory.models import (
    DreamingCheckpoint,
    DreamingLock,
    DreamingSweepMode,
    DreamingSweepNoteResult,
    DreamingSweepResult,
    DreamingSweepState,
    MemoryDocumentKind,
    MemoryIndexSyncResult,
    MemorySearchHit,
    MemorySearchResult,
    PromotionApplyResult,
    PromotionCandidate,
    PromotionPreview,
    SemanticSearchHit,
    SemanticSearchResult,
)
from controlmesh.memory.promotion import (
    apply_candidates,
    parse_promotion_candidates,
    preview_candidates,
)
from controlmesh.memory.runtime_capture import (
    capture_task_question,
    capture_task_result,
    capture_task_resume,
    capture_team_event,
    capture_transcript_turn,
    event_from_task_question,
    event_from_task_result,
    event_from_task_resume,
    event_from_team_event,
    event_from_transcript_turn,
)
from controlmesh.memory.search import search_memory_index, sync_memory_index
from controlmesh.memory.semantic import search_semantic_index, sync_semantic_index
from controlmesh.memory.store import append_dream_entry, ensure_daily_note, initialize_memory_v2

__all__ = [
    "AskParentEvent",
    "DreamingCheckpoint",
    "DreamingLock",
    "DreamingSweepMode",
    "DreamingSweepNoteResult",
    "DreamingSweepResult",
    "DreamingSweepState",
    "EvidenceRef",
    "EvidenceRefKind",
    "MemoryDocumentKind",
    "MemoryEvent",
    "MemoryEventKind",
    "MemoryIndexSyncResult",
    "MemorySearchHit",
    "MemorySearchResult",
    "PatternAnalysisResult",
    "PromotionApplyResult",
    "PromotionCandidate",
    "PromotionPreview",
    "RepeatedPattern",
    "ResumeEvent",
    "RoutingContext",
    "SemanticSearchHit",
    "SemanticSearchResult",
    "SignalCandidate",
    "SignalConfidence",
    "acquire_dream_lock",
    "append_dream_entry",
    "apply_candidates",
    "apply_daily_note_promotions",
    "apply_dreaming_sweep",
    "apply_memory_dreaming_sweep",
    "capture_event",
    "capture_event_batch",
    "capture_evidence",
    "capture_open_candidate",
    "capture_signal",
    "capture_signal_batch",
    "capture_task_question",
    "capture_task_result",
    "capture_task_resume",
    "capture_team_event",
    "capture_transcript_turn",
    "ensure_daily_note",
    "event_from_task_question",
    "event_from_task_result",
    "event_from_task_resume",
    "event_from_team_event",
    "event_from_transcript_turn",
    "expand_daily_note_skeleton",
    "find_repeated_patterns",
    "initialize_memory_v2",
    "load_checkpoints",
    "load_sweep_state",
    "parse_promotion_candidates",
    "preview_candidates",
    "preview_daily_note_promotions",
    "preview_dreaming_sweep",
    "preview_memory_dreaming_sweep",
    "release_dream_lock",
    "render_patterns_summary",
    "save_checkpoints",
    "save_sweep_state",
    "search_memory",
    "search_memory_index",
    "search_semantic_index",
    "sync_memory_index",
    "sync_memory_search",
    "sync_semantic_index",
]
