// Generated by packages/controlmesh-protocol/scripts/generate.mjs.
// Do not edit manually.

export const controlmeshSchemas = {
  "agent-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/agent-event.schema.json",
  "title": "AgentEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "agent_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.agent_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "agent_id": {
      "type": "string",
      "minLength": 1
    },
    "parent_agent": {
      "type": "string"
    },
    "role": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "agent-mailbox-message.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/agent-mailbox-message.schema.json",
  "title": "AgentMailboxMessage",
  "description": "A durable context message; received and consumed do not establish task completion or grant execution permission.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "message_id",
    "recipient_task",
    "sender_task",
    "sender_principal",
    "sequence",
    "correlation_id",
    "causation_id",
    "origin",
    "kind",
    "remaining_hops",
    "created_at",
    "expires_at",
    "payload",
    "status"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.agent_mailbox_message.v1"
    },
    "message_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "recipient_task": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "sender_task": {
      "type": [
        "string",
        "null"
      ]
    },
    "sender_principal": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "sequence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "correlation_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "causation_id": {
      "type": [
        "string",
        "null"
      ]
    },
    "origin": {
      "enum": [
        "human_request",
        "agent_message",
        "schedule",
        "recovery",
        "internal"
      ]
    },
    "kind": {
      "enum": [
        "tell",
        "ask_parent",
        "answer",
        "handoff"
      ]
    },
    "remaining_hops": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4
    },
    "created_at": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "expires_at": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    },
    "status": {
      "enum": [
        "pending",
        "received",
        "consumed",
        "expired"
      ]
    }
  }
},
  "artifact.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/artifact.schema.json",
  "title": "Artifact",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "relative_path"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.artifact.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "relative_path": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "mime": {
      "type": "string"
    },
    "size": {
      "type": [
        "integer",
        "null"
      ],
      "minimum": 0
    },
    "sha256": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent-response.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent-response.schema.json",
  "title": "AskParentResponse",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "response_id",
    "request_id",
    "task_id",
    "text",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_response.v1"
    },
    "response_id": {
      "type": "string",
      "minLength": 1
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "text": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent.schema.json",
  "title": "AskParentRequest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "request_id",
    "task_id",
    "question",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_request.v1"
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "tool_use_id": {
      "type": "string"
    },
    "parent_agent": {
      "type": "string"
    },
    "question": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "routing": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "config.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/config.schema.json",
  "title": "ControlMeshConfig",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.config.v1"
    },
    "providers": {
      "type": "object",
      "additionalProperties": true
    },
    "api": {
      "type": "object",
      "additionalProperties": true
    },
    "messengers": {
      "type": "object",
      "additionalProperties": true
    },
    "workspace": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "device-command.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-command.schema.json",
  "title": "DeviceCommand",
  "description": "Private worker transport; identities, scopes, workspace mappings and executable adapters come only from trusted configuration.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "request_id",
    "operation",
    "arguments"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_command.v1"
    },
    "request_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "operation": {
      "enum": [
        "queue",
        "inspect",
        "claim",
        "start",
        "renew",
        "dispatch",
        "observe",
        "complete",
        "unknown",
        "messages",
        "send",
        "ack",
        "release"
      ]
    },
    "arguments": {
      "type": "object"
    }
  },
  "oneOf": [
    {
      "properties": {
        "operation": {
          "const": "queue"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [],
          "properties": {}
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "inspect"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "task_id"
          ],
          "properties": {
            "task_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "claim"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "task_id",
            "revision",
            "ttl_ms",
            "assignment_digest"
          ],
          "properties": {
            "task_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "revision": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 500,
              "maximum": 30000
            },
            "assignment_digest": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "start"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "renew"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "ttl_ms"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 500,
              "maximum": 30000
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "dispatch"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "intent"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "intent": {
              "type": "object"
            },
            "manifest": {
              "$ref": "device-evidence-ref.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "observe"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "observation"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "observation": {
              "type": "object"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "complete"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "result"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "result": {
              "type": "object"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "unknown"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "reason"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "reason": {
              "type": "string",
              "pattern": "^[a-z0-9_]{1,96}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "messages"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "send"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "recipient_task",
            "kind",
            "payload",
            "causation_id",
            "ttl_ms"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "recipient_task": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "kind": {
              "enum": [
                "tell",
                "ask_parent",
                "answer",
                "handoff"
              ]
            },
            "payload": {
              "type": "object"
            },
            "causation_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 100,
              "maximum": 3600000
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "ack"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "message_id",
            "phase",
            "evidence"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "message_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "phase": {
              "enum": [
                "received",
                "consumed"
              ]
            },
            "evidence": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "release"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "reason": {
              "type": "string",
              "pattern": "^[a-z0-9_]{1,96}$"
            }
          }
        }
      }
    }
  ]
},
  "device-evidence-ref.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-evidence-ref.schema.json",
  "title": "DeviceEvidenceRef",
  "description": "Bounded reference to immutable evidence kept on the executing device. Contains no native store or workspace paths.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "device_id",
    "task_id",
    "episode_id",
    "effect_id",
    "fence",
    "assignment_digest",
    "manifest_digest"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_evidence.v1"
    },
    "device_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "task_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "episode_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "effect_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "fence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "assignment_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "manifest_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "observation_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "result_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    }
  }
},
  "device-lease-window.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-lease-window.schema.json",
  "title": "DeviceLeaseWindow",
  "description": "Freshly checked coordinator lease duration. The client starts its local deadline before sending the request, subtracts a safety margin, and never revives an expired authority.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "lease",
    "remaining_ms"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_lease_window.v1"
    },
    "lease": {
      "$ref": "execution-lease.schema.json"
    },
    "remaining_ms": {
      "type": "integer",
      "minimum": 1,
      "maximum": 30000
    }
  }
},
  "device-native-result.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-native-result.schema.json",
  "title": "DeviceNativeResult",
  "required": [
    "schema_version",
    "text",
    "output_digest",
    "read_count",
    "evidence",
    "native_session"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_native_result.v1"
    },
    "text": {
      "type": "string",
      "maxLength": 65536
    },
    "output_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "read_count": {
      "type": "integer",
      "minimum": 0,
      "maximum": 80
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    },
    "native_session": {
      "$ref": "device-native-session.schema.json"
    }
  }
},
  "device-native-session.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-native-session.schema.json",
  "title": "DeviceNativeSession",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "device_id",
    "evidence"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_native_session.v1"
    },
    "device_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    }
  }
},
  "device-observation.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-observation.schema.json",
  "title": "DeviceObservation",
  "required": [
    "schema_version",
    "evidence",
    "terminal"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_observation.v1"
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    },
    "terminal": {
      "type": "boolean"
    }
  }
},
  "device-response.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-response.schema.json",
  "title": "DeviceResponse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "request_id",
    "ok"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_response.v1"
    },
    "request_id": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 180
    },
    "ok": {
      "type": "boolean"
    },
    "data": {},
    "error": {
      "type": "string",
      "pattern": "^[a-z0-9_]{1,96}$"
    }
  },
  "oneOf": [
    {
      "properties": {
        "ok": {
          "const": true
        },
        "request_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "data"
      ],
      "not": {
        "required": [
          "error"
        ]
      }
    },
    {
      "properties": {
        "ok": {
          "const": false
        }
      },
      "required": [
        "error"
      ],
      "not": {
        "required": [
          "data"
        ]
      }
    }
  ]
},
  "doctor-result.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/doctor-result.schema.json",
  "title": "DoctorResult",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "severity",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.doctor_result.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "severity": {
      "type": "string",
      "enum": [
        "info",
        "warning",
        "error"
      ]
    },
    "message": {
      "type": "string"
    },
    "fix_hint": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "error.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/error.schema.json",
  "title": "ControlMeshError",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.error.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "message": {
      "type": "string"
    },
    "retryable": {
      "type": "boolean"
    },
    "correlation_id": {
      "type": "string"
    },
    "python_trace_id": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "execution-lease.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/execution-lease.schema.json",
  "title": "ExecutionLease",
  "description": "Coordinator-issued lease. Worker clocks and request-body identities are not authority.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "task_id",
    "episode_id",
    "device_id",
    "fence",
    "lease_until"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.execution_lease.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "episode_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "device_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "fence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "lease_until": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    }
  }
},
  "log-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/log-event.schema.json",
  "title": "LogEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "level",
    "source",
    "message",
    "timestamp"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.log_event.v1"
    },
    "level": {
      "type": "string",
      "enum": [
        "debug",
        "info",
        "warning",
        "error"
      ]
    },
    "source": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timestamp": {
      "type": [
        "number",
        "string"
      ]
    },
    "correlation_id": {
      "type": "string"
    }
  }
},
  "memory-record.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/memory-record.schema.json",
  "title": "MemoryRecord",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "record_id",
    "source_file",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.memory_record.v1"
    },
    "record_id": {
      "type": "string",
      "minLength": 1
    },
    "source_file": {
      "type": "string",
      "minLength": 1
    },
    "section": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "promotion_state": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "provider-capability.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-capability.schema.json",
  "title": "ProviderCapability",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "name",
    "available",
    "health"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_capability.v1"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "available": {
      "type": "boolean"
    },
    "version": {
      "type": "string"
    },
    "last_checked_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "health": {
      "type": "string",
      "enum": [
        "ok",
        "degraded",
        "unavailable"
      ]
    },
    "detail": {
      "type": "string"
    },
    "capabilities": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "provider-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-event.schema.json",
  "title": "ProviderEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "provider",
    "kind",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_event.v1"
    },
    "provider": {
      "type": "string",
      "minLength": 1
    },
    "kind": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "pid": {
      "type": [
        "integer",
        "null"
      ]
    },
    "command": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "text": {
      "type": "string"
    },
    "event_type": {
      "type": "string"
    },
    "payload": {},
    "idle_for_s": {
      "type": "number"
    },
    "elapsed_s": {
      "type": "number"
    },
    "exit_code": {
      "type": [
        "integer",
        "null"
      ]
    },
    "reason": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timed_out": {
      "type": "boolean"
    }
  }
},
  "runtime-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/runtime-event.schema.json",
  "title": "RuntimeEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "session_key",
    "event_type",
    "created_at",
    "transport",
    "chat_id"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.runtime_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "session_key": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    }
  }
},
  "task-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-event.schema.json",
  "title": "TaskEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "task_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "task-state.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-state.schema.json",
  "title": "TaskState",
  "description": "Stable task lifecycle states exposed at the ControlMesh protocol boundary.",
  "type": "string",
  "enum": [
    "running",
    "done",
    "failed",
    "cancelled",
    "waiting",
    "detached",
    "recovering",
    "stale",
    "timeout"
  ]
},
  "task.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task.schema.json",
  "title": "Task",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "chat_id",
    "parent_agent",
    "status",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "source_kind": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "parent_agent": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "prompt_preview": {
      "type": "string"
    },
    "provider": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "transport": {
      "type": "string"
    },
    "topology": {
      "type": "string"
    },
    "session_id": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "completed_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "elapsed_seconds": {
      "type": "number"
    },
    "result_preview": {
      "type": "string"
    },
    "last_question": {
      "type": "string"
    }
  }
},
  "topology.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/topology.schema.json",
  "title": "Topology",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "topology_id",
    "nodes",
    "edges"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.topology.v1"
    },
    "topology_id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "kind"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "label": {
            "type": "string"
          },
          "status": {
            "type": [
              "string",
              "null"
            ]
          },
          "role": {
            "type": [
              "string",
              "null"
            ]
          },
          "provider": {
            "type": [
              "string",
              "null"
            ]
          },
          "owner": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "source",
          "target",
          "kind"
        ],
        "properties": {
          "source": {
            "type": "string",
            "minLength": 1
          },
          "target": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  }
},
  "transport-message.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/transport-message.schema.json",
  "title": "TransportMessage",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "transport",
    "message_id",
    "chat_id",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.transport_message.v1"
    },
    "transport": {
      "type": "string",
      "minLength": 1
    },
    "message_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "sender_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "text": {
      "type": "string"
    },
    "command": {
      "type": "string"
    },
    "raw_payload": {},
    "created_at": {
      "type": "string"
    }
  }
},
  "workspace-manifest.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/workspace-manifest.schema.json",
  "title": "WorkspaceManifest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "workspace_root",
    "paths"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.workspace_manifest.v1"
    },
    "workspace_root": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
} as const;
