// Generated by packages/controlmesh-protocol/scripts/generate.mjs.
// Do not edit manually.

export const controlmeshSchemas = {
  "agent-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/agent-event.schema.json",
  "title": "AgentEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "agent_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.agent_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "agent_id": {
      "type": "string",
      "minLength": 1
    },
    "parent_agent": {
      "type": "string"
    },
    "role": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "agent-mailbox-message.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/agent-mailbox-message.schema.json",
  "title": "AgentMailboxMessage",
  "description": "A durable context message; received and consumed do not establish task completion or grant execution permission.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "message_id",
    "recipient_task",
    "sender_task",
    "sender_principal",
    "sequence",
    "correlation_id",
    "causation_id",
    "origin",
    "kind",
    "remaining_hops",
    "created_at",
    "expires_at",
    "payload",
    "status"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.agent_mailbox_message.v1"
    },
    "message_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "recipient_task": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "sender_task": {
      "type": [
        "string",
        "null"
      ]
    },
    "sender_principal": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "sequence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "correlation_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "causation_id": {
      "type": [
        "string",
        "null"
      ]
    },
    "origin": {
      "enum": [
        "human_request",
        "agent_message",
        "schedule",
        "recovery",
        "internal"
      ]
    },
    "kind": {
      "enum": [
        "tell",
        "ask_parent",
        "answer",
        "handoff"
      ]
    },
    "remaining_hops": {
      "type": "integer",
      "minimum": 0,
      "maximum": 4
    },
    "created_at": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "expires_at": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    },
    "status": {
      "enum": [
        "pending",
        "received",
        "consumed",
        "expired"
      ]
    }
  }
},
  "artifact.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/artifact.schema.json",
  "title": "Artifact",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "relative_path"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.artifact.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "relative_path": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "mime": {
      "type": "string"
    },
    "size": {
      "type": [
        "integer",
        "null"
      ],
      "minimum": 0
    },
    "sha256": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent-response.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent-response.schema.json",
  "title": "AskParentResponse",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "response_id",
    "request_id",
    "task_id",
    "text",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_response.v1"
    },
    "response_id": {
      "type": "string",
      "minLength": 1
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "text": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent.schema.json",
  "title": "AskParentRequest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "request_id",
    "task_id",
    "question",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_request.v1"
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "tool_use_id": {
      "type": "string"
    },
    "parent_agent": {
      "type": "string"
    },
    "question": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "routing": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "config.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/config.schema.json",
  "title": "ControlMeshConfig",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.config.v1"
    },
    "providers": {
      "type": "object",
      "additionalProperties": true
    },
    "api": {
      "type": "object",
      "additionalProperties": true
    },
    "messengers": {
      "type": "object",
      "additionalProperties": true
    },
    "workspace": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "delivery-receipt.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/delivery-receipt.schema.json",
  "title": "DeliveryReceipt",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "delivery_id",
    "envelope_digest",
    "target_digest",
    "adapter_digest",
    "remote_message_id"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.delivery_receipt.v1"
    },
    "delivery_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "envelope_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "target_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "adapter_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "remote_message_id": {
      "type": "string",
      "maxLength": 192,
      "minLength": 1
    }
  }
},
  "delivery-target.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/delivery-target.schema.json",
  "title": "DeliveryTarget",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "transport",
    "chat_id",
    "topic_id",
    "thread_id"
  ],
  "properties": {
    "transport": {
      "type": "string",
      "pattern": "^[a-z0-9_-]{1,32}$"
    },
    "chat_id": {
      "type": "string",
      "maxLength": 128,
      "minLength": 1
    },
    "topic_id": {
      "type": "string",
      "maxLength": 128
    },
    "thread_id": {
      "type": "string",
      "maxLength": 128
    }
  }
},
  "device-command.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-command.schema.json",
  "title": "DeviceCommand",
  "description": "Private worker transport; identities, scopes, workspace mappings and executable adapters come only from trusted configuration.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "request_id",
    "operation",
    "arguments"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_command.v1"
    },
    "request_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "operation": {
      "enum": [
        "queue",
        "inspect",
        "claim",
        "start",
        "renew",
        "dispatch",
        "observe",
        "complete",
        "unknown",
        "messages",
        "send",
        "ack",
        "release",
        "reconciliation",
        "reconcile",
        "native_call",
        "native_input",
        "queue_page"
      ]
    },
    "arguments": {
      "type": "object"
    }
  },
  "oneOf": [
    {
      "properties": {
        "operation": {
          "const": "queue"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [],
          "properties": {}
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "inspect"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "task_id"
          ],
          "properties": {
            "task_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "claim"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "task_id",
            "revision",
            "ttl_ms",
            "assignment_digest"
          ],
          "properties": {
            "task_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "revision": {
              "type": "integer",
              "minimum": 0,
              "maximum": 9007199254740991
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 500,
              "maximum": 30000
            },
            "assignment_digest": {
              "type": "string",
              "pattern": "^[a-f0-9]{64}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "start"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "renew"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "ttl_ms"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 500,
              "maximum": 30000
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "dispatch"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "intent"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "intent": {
              "type": "object"
            },
            "manifest": {
              "$ref": "device-evidence-ref.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "observe"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "observation"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "observation": {
              "type": "object"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "complete"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "result"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "result": {
              "type": "object"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "unknown"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "reason"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "reason": {
              "type": "string",
              "pattern": "^[a-z0-9_]{1,96}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "messages"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "send"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "recipient_task",
            "kind",
            "payload",
            "causation_id",
            "ttl_ms"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "recipient_task": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "kind": {
              "enum": [
                "tell",
                "ask_parent",
                "answer",
                "handoff"
              ]
            },
            "payload": {
              "type": "object"
            },
            "causation_id": {
              "type": [
                "string",
                "null"
              ]
            },
            "ttl_ms": {
              "type": "integer",
              "minimum": 100,
              "maximum": 3600000
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "ack"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "message_id",
            "phase",
            "evidence"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "message_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "phase": {
              "enum": [
                "received",
                "consumed"
              ]
            },
            "evidence": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "release"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "reason": {
              "type": "string",
              "pattern": "^[a-z0-9_]{1,96}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "reconciliation"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "challenge_id"
          ],
          "properties": {
            "challenge_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "reconcile"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "report"
          ],
          "properties": {
            "report": {
              "$ref": "device-reconciliation-report.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "native_call"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease",
            "effect_id",
            "tool",
            "input"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            },
            "effect_id": {
              "type": "string",
              "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
            },
            "tool": {
              "enum": [
                "controlmesh_send",
                "controlmesh_ask_parent",
                "controlmesh_receive",
                "controlmesh_answer"
              ]
            },
            "input": {
              "type": "object",
              "required": [
                "request_id"
              ],
              "properties": {
                "request_id": {
                  "type": "string",
                  "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
                }
              }
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "native_input"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "lease"
          ],
          "properties": {
            "lease": {
              "$ref": "execution-lease.schema.json"
            }
          }
        }
      }
    },
    {
      "properties": {
        "operation": {
          "const": "queue_page"
        },
        "arguments": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "after"
          ],
          "properties": {
            "after": {
              "anyOf": [
                {
                  "type": "string",
                  "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        }
      }
    }
  ]
},
  "device-completion-proof.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-completion-proof.schema.json",
  "title": "DeviceCompletionProof",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "requirements_digest",
    "sha256"
  ],
  "properties": {
    "requirements_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "sha256": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "type": "string",
        "pattern": "^[a-f0-9]{64}$"
      }
    }
  }
},
  "device-evidence-ref.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-evidence-ref.schema.json",
  "title": "DeviceEvidenceRef",
  "description": "Bounded reference to immutable evidence kept on the executing device. Contains no native store or workspace paths.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "device_id",
    "task_id",
    "episode_id",
    "effect_id",
    "fence",
    "assignment_digest",
    "manifest_digest"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_evidence.v1"
    },
    "device_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "task_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "episode_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "effect_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "fence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "assignment_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "manifest_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "observation_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "result_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "communication": {
      "$ref": "native-agent-scope.schema.json"
    },
    "mailbox_delivery": {
      "$ref": "native-mailbox-binding.schema.json"
    },
    "workspace_write": {
      "$ref": "device-workspace-binding.schema.json"
    }
  }
},
  "device-lease-window.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-lease-window.schema.json",
  "title": "DeviceLeaseWindow",
  "description": "Freshly checked coordinator lease duration. The client starts its local deadline before sending the request, subtracts a safety margin, and never revives an expired authority.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "lease",
    "remaining_ms"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_lease_window.v1"
    },
    "lease": {
      "$ref": "execution-lease.schema.json"
    },
    "remaining_ms": {
      "type": "integer",
      "minimum": 1,
      "maximum": 30000
    }
  }
},
  "device-native-adoption.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-native-adoption.schema.json",
  "title": "DeviceNativeAdoption",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "device_id",
    "adoption_id",
    "context_digest"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_native_adoption.v1"
    },
    "device_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "adoption_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "context_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    }
  }
},
  "device-native-result.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-native-result.schema.json",
  "title": "DeviceNativeResult",
  "required": [
    "schema_version",
    "text",
    "output_digest",
    "read_count",
    "evidence",
    "native_session"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_native_result.v1"
    },
    "text": {
      "type": "string",
      "maxLength": 65536
    },
    "output_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "read_count": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    },
    "native_session": {
      "$ref": "device-native-session.schema.json"
    },
    "communication": {
      "$ref": "native-agent-proof.schema.json"
    },
    "mailbox_delivery": {
      "$ref": "native-mailbox-proof.schema.json"
    },
    "workspace_write": {
      "$ref": "device-workspace-proof.schema.json"
    },
    "completion": {
      "$ref": "device-completion-proof.schema.json"
    }
  }
},
  "device-native-session.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-native-session.schema.json",
  "title": "DeviceNativeSession",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "device_id",
    "evidence"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_native_session.v1"
    },
    "device_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    }
  }
},
  "device-observation.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-observation.schema.json",
  "title": "DeviceObservation",
  "required": [
    "schema_version",
    "evidence",
    "terminal"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_observation.v1"
    },
    "evidence": {
      "$ref": "device-evidence-ref.schema.json"
    },
    "terminal": {
      "type": "boolean"
    }
  }
},
  "device-reconciliation-challenge.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-reconciliation-challenge.schema.json",
  "title": "DeviceReconciliationChallenge",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "challenge_id",
    "task_revision",
    "task_fence",
    "manifest",
    "execution_digest",
    "workspace_id",
    "capability",
    "expires_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_reconciliation_challenge.v1"
    },
    "challenge_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "task_revision": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "task_fence": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "manifest": {
      "$ref": "device-evidence-ref.schema.json"
    },
    "execution_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "workspace_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "capability": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "expires_at": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    }
  }
},
  "device-reconciliation-report.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-reconciliation-report.schema.json",
  "title": "DeviceReconciliationReport",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "challenge_id",
    "challenge_digest",
    "observation",
    "result"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_reconciliation_report.v1"
    },
    "challenge_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "challenge_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "observation": {
      "$ref": "device-observation.schema.json"
    },
    "result": {
      "$ref": "device-native-result.schema.json"
    }
  }
},
  "device-response.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-response.schema.json",
  "title": "DeviceResponse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "request_id",
    "ok"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.device_response.v1"
    },
    "request_id": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 180
    },
    "ok": {
      "type": "boolean"
    },
    "data": {},
    "error": {
      "type": "string",
      "pattern": "^[a-z0-9_]{1,96}$"
    }
  },
  "oneOf": [
    {
      "properties": {
        "ok": {
          "const": true
        },
        "request_id": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "data"
      ],
      "not": {
        "required": [
          "error"
        ]
      }
    },
    {
      "properties": {
        "ok": {
          "const": false
        }
      },
      "required": [
        "error"
      ],
      "not": {
        "required": [
          "data"
        ]
      }
    }
  ]
},
  "device-workspace-binding.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-workspace-binding.schema.json",
  "title": "DeviceWorkspaceBinding",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "profile_digest",
    "workflow_binding"
  ],
  "properties": {
    "profile_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "workflow_binding": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[a-f0-9]{64}$"
    }
  }
},
  "device-workspace-proof.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/device-workspace-proof.schema.json",
  "title": "DeviceWorkspaceProof",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "profile_digest",
    "proposal_digest",
    "changed_count"
  ],
  "properties": {
    "profile_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "proposal_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "changed_count": {
      "type": "integer",
      "minimum": 0,
      "maximum": 2048
    },
    "specmesh": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "snapshot_digest",
        "status",
        "closeout_verified"
      ],
      "properties": {
        "snapshot_digest": {
          "type": "string",
          "pattern": "^[a-f0-9]{64}$"
        },
        "status": {
          "const": "pass"
        },
        "closeout_verified": {
          "const": false
        }
      }
    }
  }
},
  "doctor-result.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/doctor-result.schema.json",
  "title": "DoctorResult",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "severity",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.doctor_result.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "severity": {
      "type": "string",
      "enum": [
        "info",
        "warning",
        "error"
      ]
    },
    "message": {
      "type": "string"
    },
    "fix_hint": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "error.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/error.schema.json",
  "title": "ControlMeshError",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.error.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "message": {
      "type": "string"
    },
    "retryable": {
      "type": "boolean"
    },
    "correlation_id": {
      "type": "string"
    },
    "python_trace_id": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "execution-lease.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/execution-lease.schema.json",
  "title": "ExecutionLease",
  "description": "Coordinator-issued lease. Worker clocks and request-body identities are not authority.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "task_id",
    "episode_id",
    "device_id",
    "fence",
    "lease_until"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.execution_lease.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "episode_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "device_id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 192
    },
    "fence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "lease_until": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    }
  }
},
  "feishu-incoming.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/feishu-incoming.schema.json",
  "title": "FeishuIncomingMessage",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "app_id",
    "event_id",
    "message_id",
    "sender_id",
    "chat_id",
    "thread_id",
    "root_id",
    "text",
    "created_at",
    "source_scope",
    "mentions_local_bot"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.feishu_incoming.v1",
      "type": "string"
    },
    "app_id": {
      "type": "string",
      "pattern": "^cli_[A-Za-z0-9_-]{1,120}$"
    },
    "event_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{1,128}$"
    },
    "message_id": {
      "type": "string",
      "pattern": "^om_[A-Za-z0-9_-]{1,120}$"
    },
    "sender_id": {
      "type": "string",
      "pattern": "^ou_[A-Za-z0-9_-]{1,120}$"
    },
    "chat_id": {
      "type": "string",
      "pattern": "^oc_[A-Za-z0-9_-]{1,120}$"
    },
    "thread_id": {
      "type": "string",
      "pattern": "^(?:|th_[A-Za-z0-9_-]{1,120})$"
    },
    "root_id": {
      "type": "string",
      "pattern": "^(?:|om_[A-Za-z0-9_-]{1,120})$"
    },
    "text": {
      "type": "string",
      "minLength": 1,
      "maxLength": 32768
    },
    "created_at": {
      "type": "integer",
      "minimum": 1
    },
    "source_scope": {
      "type": "string",
      "enum": [
        "direct_message",
        "group_message"
      ]
    },
    "mentions_local_bot": {
      "type": "boolean"
    }
  }
},
  "log-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/log-event.schema.json",
  "title": "LogEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "level",
    "source",
    "message",
    "timestamp"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.log_event.v1"
    },
    "level": {
      "type": "string",
      "enum": [
        "debug",
        "info",
        "warning",
        "error"
      ]
    },
    "source": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timestamp": {
      "type": [
        "number",
        "string"
      ]
    },
    "correlation_id": {
      "type": "string"
    }
  }
},
  "memory-record.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/memory-record.schema.json",
  "title": "MemoryRecord",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "record_id",
    "source_file",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.memory_record.v1"
    },
    "record_id": {
      "type": "string",
      "minLength": 1
    },
    "source_file": {
      "type": "string",
      "minLength": 1
    },
    "section": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "promotion_state": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "native-agent-call-receipt.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-agent-call-receipt.schema.json",
  "title": "NativeAgentCallReceipt",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "call_id",
    "tool",
    "input_digest",
    "output_digest"
  ],
  "properties": {
    "call_id": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "tool": {
      "enum": [
        "controlmesh_send",
        "controlmesh_ask_parent",
        "controlmesh_receive",
        "controlmesh_answer"
      ]
    },
    "input_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "output_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    }
  }
},
  "native-agent-proof.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-agent-proof.schema.json",
  "title": "NativeAgentProof",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "call_receipts"
  ],
  "properties": {
    "call_receipts": {
      "type": "array",
      "maxItems": 32,
      "items": {
        "$ref": "native-agent-call-receipt.schema.json"
      }
    }
  }
},
  "native-agent-scope.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-agent-scope.schema.json",
  "title": "NativeAgentScope",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "task_id",
    "episode_id",
    "fence",
    "peer_tasks",
    "parent_task",
    "client_digest"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.native_agent_scope.v1"
    },
    "task_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "episode_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "fence": {
      "type": "integer",
      "minimum": 1,
      "maximum": 9007199254740991
    },
    "peer_tasks": {
      "type": "array",
      "maxItems": 16,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
      }
    },
    "parent_task": {
      "type": [
        "string",
        "null"
      ],
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "client_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    }
  }
},
  "native-mailbox-batch.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-mailbox-batch.schema.json",
  "title": "NativeMailboxBatch",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "task_id",
    "messages"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.native_mailbox.v1"
    },
    "task_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "messages": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "$ref": "agent-mailbox-message.schema.json"
      }
    }
  }
},
  "native-mailbox-binding.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-mailbox-binding.schema.json",
  "title": "NativeMailboxBinding",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "delivery_digest",
    "message_ids"
  ],
  "properties": {
    "delivery_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "message_ids": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
      }
    }
  }
},
  "native-mailbox-proof.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/native-mailbox-proof.schema.json",
  "title": "NativeMailboxProof",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "delivery_digest",
    "message_ids",
    "native_user_message_id"
  ],
  "properties": {
    "delivery_digest": {
      "type": "string",
      "pattern": "^[a-f0-9]{64}$"
    },
    "message_ids": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
      }
    },
    "native_user_message_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    }
  }
},
  "provider-capability.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-capability.schema.json",
  "title": "ProviderCapability",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "name",
    "available",
    "health"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_capability.v1"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "available": {
      "type": "boolean"
    },
    "version": {
      "type": "string"
    },
    "last_checked_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "health": {
      "type": "string",
      "enum": [
        "ok",
        "degraded",
        "unavailable"
      ]
    },
    "detail": {
      "type": "string"
    },
    "capabilities": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "provider-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-event.schema.json",
  "title": "ProviderEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "provider",
    "kind",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_event.v1"
    },
    "provider": {
      "type": "string",
      "minLength": 1
    },
    "kind": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "pid": {
      "type": [
        "integer",
        "null"
      ]
    },
    "command": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "text": {
      "type": "string"
    },
    "event_type": {
      "type": "string"
    },
    "payload": {},
    "idle_for_s": {
      "type": "number"
    },
    "elapsed_s": {
      "type": "number"
    },
    "exit_code": {
      "type": [
        "integer",
        "null"
      ]
    },
    "reason": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timed_out": {
      "type": "boolean"
    }
  }
},
  "runtime-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/runtime-event.schema.json",
  "title": "RuntimeEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "session_key",
    "event_type",
    "created_at",
    "transport",
    "chat_id"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.runtime_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "session_key": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    }
  }
},
  "task-completion.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-completion.schema.json",
  "title": "TaskCompletion",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "files"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task_completion.v1"
    },
    "files": {
      "type": "array",
      "minItems": 1,
      "maxItems": 32,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "path",
          "mode"
        ],
        "properties": {
          "path": {
            "type": "string",
            "minLength": 1,
            "maxLength": 1024
          },
          "mode": {
            "enum": [
              "read",
              "write"
            ]
          },
          "sha256": {
            "type": "string",
            "pattern": "^[a-f0-9]{64}$"
          }
        }
      }
    }
  }
},
  "task-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-event.schema.json",
  "title": "TaskEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "task_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "task-state.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-state.schema.json",
  "title": "TaskState",
  "description": "Stable task lifecycle states exposed at the ControlMesh protocol boundary.",
  "type": "string",
  "enum": [
    "running",
    "done",
    "failed",
    "cancelled",
    "waiting",
    "detached",
    "recovering",
    "stale",
    "timeout"
  ]
},
  "task.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task.schema.json",
  "title": "Task",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "chat_id",
    "parent_agent",
    "status",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "source_kind": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "parent_agent": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "prompt_preview": {
      "type": "string"
    },
    "provider": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "transport": {
      "type": "string"
    },
    "topology": {
      "type": "string"
    },
    "session_id": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "completed_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "elapsed_seconds": {
      "type": "number"
    },
    "result_preview": {
      "type": "string"
    },
    "last_question": {
      "type": "string"
    }
  }
},
  "team-structured-result.schema.json": {
  "description": "Schema-versioned worker result envelope for topology execution.",
  "properties": {
    "schema_version": {
      "const": 1
    },
    "status": {
      "enum": [
        "completed",
        "failed",
        "blocked",
        "needs_parent_input",
        "needs_repair"
      ]
    },
    "topology": {
      "enum": [
        "pipeline",
        "fanout_merge",
        "director_worker",
        "debate_judge"
      ]
    },
    "substage": {
      "title": "Substage",
      "type": "string",
      "minLength": 1
    },
    "worker_role": {
      "title": "Worker Role",
      "type": "string",
      "minLength": 1
    },
    "result_items": {
      "items": {
        "description": "Neutral runtime item reference preserved inside structured team results.",
        "properties": {
          "kind": {
            "enum": [
              "message",
              "tool_call",
              "tool_result",
              "interrupt",
              "dispatch",
              "phase_transition",
              "repair_note"
            ]
          },
          "ref": {
            "title": "Ref",
            "type": "string",
            "minLength": 1
          },
          "summary": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ],
            "title": "Summary"
          }
        },
        "required": [
          "kind",
          "ref",
          "summary"
        ],
        "title": "TeamResultItemRef",
        "type": "object",
        "additionalProperties": false
      },
      "title": "Result Items",
      "type": "array"
    },
    "summary": {
      "title": "Summary",
      "type": "string",
      "minLength": 1
    },
    "evidence": {
      "items": {
        "description": "Pointer to evidence selected from ControlMesh-owned runtime truth.",
        "properties": {
          "ref": {
            "title": "Ref",
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "title": "Kind",
            "type": "string",
            "minLength": 1
          },
          "summary": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ],
            "title": "Summary"
          }
        },
        "required": [
          "ref",
          "kind",
          "summary"
        ],
        "title": "TeamEvidenceRef",
        "type": "object",
        "additionalProperties": false
      },
      "title": "Evidence",
      "type": "array"
    },
    "confidence": {
      "type": [
        "number",
        "null"
      ],
      "minimum": 0,
      "maximum": 1
    },
    "artifacts": {
      "items": {
        "description": "Pointer to an artifact owned by ControlMesh task/runtime storage.",
        "properties": {
          "ref": {
            "title": "Ref",
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "title": "Kind",
            "type": "string",
            "minLength": 1
          },
          "label": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ],
            "title": "Label"
          },
          "summary": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ],
            "title": "Summary"
          }
        },
        "required": [
          "ref",
          "kind",
          "label",
          "summary"
        ],
        "title": "TeamArtifactRef",
        "type": "object",
        "additionalProperties": false
      },
      "title": "Artifacts",
      "type": "array"
    },
    "next_action": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ],
      "title": "Next Action"
    },
    "needs_parent_input": {
      "title": "Needs Parent Input",
      "type": "boolean"
    },
    "repair_hint": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ],
      "title": "Repair Hint"
    }
  },
  "required": [
    "schema_version",
    "status",
    "topology",
    "substage",
    "worker_role",
    "result_items",
    "summary",
    "evidence",
    "confidence",
    "artifacts",
    "next_action",
    "needs_parent_input",
    "repair_hint"
  ],
  "title": "TeamStructuredResult",
  "type": "object",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/team-structured-result.schema.json",
  "additionalProperties": false,
  "allOf": [
    {
      "if": {
        "properties": {
          "topology": {
            "const": "pipeline"
          }
        }
      },
      "then": {
        "properties": {
          "substage": {
            "enum": [
              "planning",
              "worker_running",
              "review_running",
              "completed",
              "failed",
              "waiting_parent",
              "repairing"
            ]
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "topology": {
            "const": "fanout_merge"
          }
        }
      },
      "then": {
        "properties": {
          "substage": {
            "enum": [
              "planning",
              "dispatching",
              "collecting",
              "reducing",
              "completed",
              "failed",
              "waiting_parent",
              "repairing"
            ]
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "topology": {
            "const": "director_worker"
          }
        }
      },
      "then": {
        "properties": {
          "substage": {
            "enum": [
              "planning",
              "dispatching",
              "collecting",
              "director_deciding",
              "waiting_parent",
              "repairing",
              "completed",
              "failed"
            ]
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "topology": {
            "const": "debate_judge"
          }
        }
      },
      "then": {
        "properties": {
          "substage": {
            "enum": [
              "planning",
              "candidate_round",
              "collecting",
              "judging",
              "waiting_parent",
              "repairing",
              "completed",
              "failed"
            ]
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "topology": {
            "enum": [
              "director_worker",
              "debate_judge"
            ]
          }
        }
      },
      "then": {
        "properties": {
          "substage": {
            "const": "collecting"
          },
          "status": {
            "enum": [
              "completed",
              "failed",
              "needs_repair"
            ]
          },
          "needs_parent_input": {
            "const": false
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "status": {
            "const": "needs_parent_input"
          }
        }
      },
      "then": {
        "properties": {
          "needs_parent_input": {
            "const": true
          }
        }
      },
      "else": {
        "properties": {
          "needs_parent_input": {
            "const": false
          }
        }
      }
    },
    {
      "if": {
        "properties": {
          "status": {
            "const": "needs_repair"
          }
        }
      },
      "then": {
        "properties": {
          "repair_hint": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  ]
},
  "team-topology-state.schema.json": {
  "description": "TaskHub-backed persisted execution state for the topology seam.",
  "properties": {
    "schema_version": {
      "const": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1,
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
    },
    "execution_id": {
      "type": "string",
      "minLength": 1,
      "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
    },
    "topology": {
      "enum": [
        "pipeline",
        "fanout_merge",
        "director_worker",
        "debate_judge"
      ]
    },
    "checkpoints": {
      "items": {
        "description": "One persisted topology execution checkpoint.",
        "properties": {
          "checkpoint_id": {
            "type": "string",
            "minLength": 1,
            "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"
          },
          "topology": {
            "enum": [
              "pipeline",
              "fanout_merge",
              "director_worker",
              "debate_judge"
            ]
          },
          "substage": {
            "type": "string",
            "minLength": 1
          },
          "phase_status": {
            "enum": [
              "pending",
              "in_progress",
              "blocked",
              "completed",
              "failed"
            ]
          },
          "active_roles": {
            "items": {
              "type": "string",
              "minLength": 1
            },
            "type": "array"
          },
          "completed_roles": {
            "items": {
              "type": "string",
              "minLength": 1
            },
            "type": "array"
          },
          "latest_summary": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ]
          },
          "waiting_on": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ]
          },
          "artifact_count": {
            "type": "integer",
            "minimum": 0
          },
          "needs_parent_input": {
            "type": "boolean"
          },
          "repair_state": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ]
          },
          "round_index": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "null"
              }
            ]
          },
          "round_limit": {
            "anyOf": [
              {
                "type": "integer",
                "minimum": 1
              },
              {
                "type": "null"
              }
            ]
          },
          "result": {
            "anyOf": [
              {
                "description": "Schema-versioned worker result envelope for topology execution.",
                "properties": {
                  "schema_version": {
                    "const": 1
                  },
                  "status": {
                    "enum": [
                      "completed",
                      "failed",
                      "blocked",
                      "needs_parent_input",
                      "needs_repair"
                    ]
                  },
                  "topology": {
                    "enum": [
                      "pipeline",
                      "fanout_merge",
                      "director_worker",
                      "debate_judge"
                    ]
                  },
                  "substage": {
                    "title": "Substage",
                    "type": "string",
                    "minLength": 1
                  },
                  "worker_role": {
                    "title": "Worker Role",
                    "type": "string",
                    "minLength": 1
                  },
                  "result_items": {
                    "items": {
                      "description": "Neutral runtime item reference preserved inside structured team results.",
                      "properties": {
                        "kind": {
                          "enum": [
                            "message",
                            "tool_call",
                            "tool_result",
                            "interrupt",
                            "dispatch",
                            "phase_transition",
                            "repair_note"
                          ]
                        },
                        "ref": {
                          "title": "Ref",
                          "type": "string",
                          "minLength": 1
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "title": "Summary"
                        }
                      },
                      "required": [
                        "kind",
                        "ref",
                        "summary"
                      ],
                      "title": "TeamResultItemRef",
                      "type": "object",
                      "additionalProperties": false
                    },
                    "title": "Result Items",
                    "type": "array"
                  },
                  "summary": {
                    "title": "Summary",
                    "type": "string",
                    "minLength": 1
                  },
                  "evidence": {
                    "items": {
                      "description": "Pointer to evidence selected from ControlMesh-owned runtime truth.",
                      "properties": {
                        "ref": {
                          "title": "Ref",
                          "type": "string",
                          "minLength": 1
                        },
                        "kind": {
                          "title": "Kind",
                          "type": "string",
                          "minLength": 1
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "title": "Summary"
                        }
                      },
                      "required": [
                        "ref",
                        "kind",
                        "summary"
                      ],
                      "title": "TeamEvidenceRef",
                      "type": "object",
                      "additionalProperties": false
                    },
                    "title": "Evidence",
                    "type": "array"
                  },
                  "confidence": {
                    "type": [
                      "number",
                      "null"
                    ],
                    "minimum": 0,
                    "maximum": 1
                  },
                  "artifacts": {
                    "items": {
                      "description": "Pointer to an artifact owned by ControlMesh task/runtime storage.",
                      "properties": {
                        "ref": {
                          "title": "Ref",
                          "type": "string",
                          "minLength": 1
                        },
                        "kind": {
                          "title": "Kind",
                          "type": "string",
                          "minLength": 1
                        },
                        "label": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "title": "Label"
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ],
                          "title": "Summary"
                        }
                      },
                      "required": [
                        "ref",
                        "kind",
                        "label",
                        "summary"
                      ],
                      "title": "TeamArtifactRef",
                      "type": "object",
                      "additionalProperties": false
                    },
                    "title": "Artifacts",
                    "type": "array"
                  },
                  "next_action": {
                    "anyOf": [
                      {
                        "type": "string",
                        "minLength": 1
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "title": "Next Action"
                  },
                  "needs_parent_input": {
                    "title": "Needs Parent Input",
                    "type": "boolean"
                  },
                  "repair_hint": {
                    "anyOf": [
                      {
                        "type": "string",
                        "minLength": 1
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "title": "Repair Hint"
                  }
                },
                "required": [
                  "schema_version",
                  "status",
                  "topology",
                  "substage",
                  "worker_role",
                  "result_items",
                  "summary",
                  "evidence",
                  "confidence",
                  "artifacts",
                  "next_action",
                  "needs_parent_input",
                  "repair_hint"
                ],
                "title": "TeamStructuredResult",
                "type": "object",
                "additionalProperties": false,
                "allOf": [
                  {
                    "if": {
                      "properties": {
                        "topology": {
                          "const": "pipeline"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "substage": {
                          "enum": [
                            "planning",
                            "worker_running",
                            "review_running",
                            "completed",
                            "failed",
                            "waiting_parent",
                            "repairing"
                          ]
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "topology": {
                          "const": "fanout_merge"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "substage": {
                          "enum": [
                            "planning",
                            "dispatching",
                            "collecting",
                            "reducing",
                            "completed",
                            "failed",
                            "waiting_parent",
                            "repairing"
                          ]
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "topology": {
                          "const": "director_worker"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "substage": {
                          "enum": [
                            "planning",
                            "dispatching",
                            "collecting",
                            "director_deciding",
                            "waiting_parent",
                            "repairing",
                            "completed",
                            "failed"
                          ]
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "topology": {
                          "const": "debate_judge"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "substage": {
                          "enum": [
                            "planning",
                            "candidate_round",
                            "collecting",
                            "judging",
                            "waiting_parent",
                            "repairing",
                            "completed",
                            "failed"
                          ]
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "topology": {
                          "enum": [
                            "director_worker",
                            "debate_judge"
                          ]
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "substage": {
                          "const": "collecting"
                        },
                        "status": {
                          "enum": [
                            "completed",
                            "failed",
                            "needs_repair"
                          ]
                        },
                        "needs_parent_input": {
                          "const": false
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "status": {
                          "const": "needs_parent_input"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "needs_parent_input": {
                          "const": true
                        }
                      }
                    },
                    "else": {
                      "properties": {
                        "needs_parent_input": {
                          "const": false
                        }
                      }
                    }
                  },
                  {
                    "if": {
                      "properties": {
                        "status": {
                          "const": "needs_repair"
                        }
                      }
                    },
                    "then": {
                      "properties": {
                        "repair_hint": {
                          "type": "string",
                          "minLength": 1
                        }
                      }
                    }
                  }
                ]
              },
              {
                "type": "null"
              }
            ]
          },
          "reduced_result": {
            "anyOf": [
              {
                "description": "Reduced topology boundary kept separate from worker-level envelopes.",
                "properties": {
                  "schema_version": {
                    "const": 1
                  },
                  "topology": {
                    "enum": [
                      "pipeline",
                      "fanout_merge",
                      "director_worker",
                      "debate_judge"
                    ]
                  },
                  "final_status": {
                    "enum": [
                      "completed",
                      "failed",
                      "blocked",
                      "needs_parent_input",
                      "needs_repair"
                    ]
                  },
                  "reduced_summary": {
                    "type": "string",
                    "minLength": 1
                  },
                  "selected_evidence": {
                    "items": {
                      "description": "Pointer to evidence selected from ControlMesh-owned runtime truth.",
                      "properties": {
                        "ref": {
                          "type": "string",
                          "minLength": 1
                        },
                        "kind": {
                          "type": "string",
                          "minLength": 1
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ]
                        }
                      },
                      "required": [
                        "ref",
                        "kind",
                        "summary"
                      ],
                      "type": "object",
                      "additionalProperties": false
                    },
                    "type": "array"
                  },
                  "selected_artifacts": {
                    "items": {
                      "description": "Pointer to an artifact owned by ControlMesh task/runtime storage.",
                      "properties": {
                        "ref": {
                          "type": "string",
                          "minLength": 1
                        },
                        "kind": {
                          "type": "string",
                          "minLength": 1
                        },
                        "label": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ]
                        },
                        "summary": {
                          "anyOf": [
                            {
                              "type": "string",
                              "minLength": 1
                            },
                            {
                              "type": "null"
                            }
                          ]
                        }
                      },
                      "required": [
                        "ref",
                        "kind",
                        "label",
                        "summary"
                      ],
                      "type": "object",
                      "additionalProperties": false
                    },
                    "type": "array"
                  },
                  "next_action": {
                    "anyOf": [
                      {
                        "type": "string",
                        "minLength": 1
                      },
                      {
                        "type": "null"
                      }
                    ]
                  }
                },
                "required": [
                  "schema_version",
                  "topology",
                  "final_status",
                  "reduced_summary",
                  "selected_evidence",
                  "selected_artifacts",
                  "next_action"
                ],
                "type": "object",
                "additionalProperties": false
              },
              {
                "type": "null"
              }
            ]
          },
          "recorded_at": {
            "anyOf": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "null"
              }
            ]
          }
        },
        "required": [
          "checkpoint_id",
          "topology",
          "substage",
          "phase_status",
          "active_roles",
          "completed_roles",
          "latest_summary",
          "waiting_on",
          "artifact_count",
          "needs_parent_input",
          "repair_state",
          "round_index",
          "round_limit",
          "result",
          "reduced_result",
          "recorded_at"
        ],
        "type": "object",
        "additionalProperties": false,
        "allOf": [
          {
            "if": {
              "properties": {
                "topology": {
                  "const": "pipeline"
                }
              }
            },
            "then": {
              "properties": {
                "substage": {
                  "enum": [
                    "planning",
                    "worker_running",
                    "review_running",
                    "completed",
                    "failed",
                    "waiting_parent",
                    "repairing"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "topology": {
                  "const": "fanout_merge"
                }
              }
            },
            "then": {
              "properties": {
                "substage": {
                  "enum": [
                    "planning",
                    "dispatching",
                    "collecting",
                    "reducing",
                    "completed",
                    "failed",
                    "waiting_parent",
                    "repairing"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "topology": {
                  "const": "director_worker"
                }
              }
            },
            "then": {
              "properties": {
                "substage": {
                  "enum": [
                    "planning",
                    "dispatching",
                    "collecting",
                    "director_deciding",
                    "waiting_parent",
                    "repairing",
                    "completed",
                    "failed"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "topology": {
                  "const": "debate_judge"
                }
              }
            },
            "then": {
              "properties": {
                "substage": {
                  "enum": [
                    "planning",
                    "candidate_round",
                    "collecting",
                    "judging",
                    "waiting_parent",
                    "repairing",
                    "completed",
                    "failed"
                  ]
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "needs_parent_input": {
                  "const": true
                }
              }
            },
            "then": {
              "properties": {
                "waiting_on": {
                  "type": "string",
                  "minLength": 1
                }
              }
            }
          }
        ]
      },
      "type": "array",
      "minItems": 1
    },
    "interruption": {
      "description": "Interruption/resume boundary carried by the execution seam from day one.",
      "properties": {
        "status": {
          "enum": [
            "idle",
            "waiting_parent"
          ]
        },
        "requested_by_role": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "question": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "waiting_on": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "raised_at": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "resume_substage": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "resume_phase_status": {
          "anyOf": [
            {
              "enum": [
                "pending",
                "in_progress",
                "blocked",
                "completed",
                "failed"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "resume_count": {
          "type": "integer",
          "minimum": 0
        },
        "last_parent_input": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "last_resumed_at": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "requested_by_role",
        "question",
        "waiting_on",
        "raised_at",
        "resume_substage",
        "resume_phase_status",
        "resume_count",
        "last_parent_input",
        "last_resumed_at"
      ],
      "allOf": [
        {
          "if": {
            "properties": {
              "status": {
                "const": "waiting_parent"
              }
            }
          },
          "then": {
            "properties": {
              "requested_by_role": {
                "type": "string",
                "minLength": 1
              },
              "question": {
                "type": "string",
                "minLength": 1
              },
              "waiting_on": {
                "type": "string",
                "minLength": 1
              },
              "raised_at": {
                "type": "string",
                "minLength": 1
              },
              "resume_substage": {
                "type": "string",
                "minLength": 1
              }
            }
          }
        }
      ]
    },
    "created_at": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "updated_at": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "schema_version",
    "task_id",
    "execution_id",
    "topology",
    "checkpoints",
    "interruption",
    "created_at",
    "updated_at"
  ],
  "type": "object",
  "additionalProperties": false,
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://controlmesh.dev/schemas/v1/team-topology-state.schema.json",
  "title": "TeamTopologyState"
},
  "terminal-delivery.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/terminal-delivery.schema.json",
  "title": "TerminalDelivery",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "delivery_id",
    "task_id",
    "event_seq",
    "task_revision",
    "fence",
    "status",
    "origin",
    "command_origin",
    "execution_context",
    "target",
    "text",
    "output_policy",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.terminal_delivery.v1"
    },
    "delivery_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "task_id": {
      "type": "string",
      "pattern": "^[A-Za-z0-9][A-Za-z0-9_.:@-]{0,191}$"
    },
    "event_seq": {
      "type": "integer",
      "minimum": 1
    },
    "task_revision": {
      "type": "integer",
      "minimum": 1
    },
    "fence": {
      "type": "integer",
      "minimum": 0
    },
    "status": {
      "enum": [
        "done",
        "failed",
        "cancelled"
      ]
    },
    "origin": {
      "const": "task_result"
    },
    "command_origin": {
      "enum": [
        "human_request",
        "agent_message",
        "schedule",
        "recovery",
        "internal"
      ]
    },
    "execution_context": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "trace_id",
        "origin",
        "source_scope",
        "transport",
        "source_ref"
      ],
      "properties": {
        "trace_id": {
          "type": "string",
          "pattern": "^[a-f0-9]{32}$"
        },
        "origin": {
          "enum": [
            "background",
            "cron",
            "webhook_wake",
            "webhook_cron",
            "heartbeat",
            "interagent",
            "task_result",
            "task_question",
            "user",
            "api"
          ]
        },
        "source_scope": {
          "enum": [
            "local_foreground",
            "direct_message",
            "group_message",
            "bot_handoff",
            "api",
            "cron",
            "webhook",
            "heartbeat",
            "background_task",
            "task_result"
          ]
        },
        "transport": {
          "type": "string",
          "pattern": "^[a-z0-9_-]{1,32}$"
        },
        "source_ref": {
          "type": "string",
          "pattern": "^([a-f0-9]{24})?$"
        }
      }
    },
    "target": {
      "$ref": "delivery-target.schema.json"
    },
    "text": {
      "type": "string",
      "maxLength": 65536,
      "minLength": 1
    },
    "output_policy": {
      "enum": [
        "summarized_only",
        "full"
      ]
    },
    "created_at": {
      "type": "integer",
      "minimum": 0
    }
  }
},
  "topology.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/topology.schema.json",
  "title": "Topology",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "topology_id",
    "nodes",
    "edges"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.topology.v1"
    },
    "topology_id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "kind"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "label": {
            "type": "string"
          },
          "status": {
            "type": [
              "string",
              "null"
            ]
          },
          "role": {
            "type": [
              "string",
              "null"
            ]
          },
          "provider": {
            "type": [
              "string",
              "null"
            ]
          },
          "owner": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "source",
          "target",
          "kind"
        ],
        "properties": {
          "source": {
            "type": "string",
            "minLength": 1
          },
          "target": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  }
},
  "transport-message.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/transport-message.schema.json",
  "title": "TransportMessage",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "transport",
    "message_id",
    "chat_id",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.transport_message.v1"
    },
    "transport": {
      "type": "string",
      "minLength": 1
    },
    "message_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "sender_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "text": {
      "type": "string"
    },
    "command": {
      "type": "string"
    },
    "raw_payload": {},
    "created_at": {
      "type": "string"
    }
  }
},
  "workspace-manifest.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/workspace-manifest.schema.json",
  "title": "WorkspaceManifest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "workspace_root",
    "paths"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.workspace_manifest.v1"
    },
    "workspace_root": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
} as const;
