// Generated by packages/controlmesh-protocol/scripts/generate.mjs.
// Do not edit manually.

export const controlmeshSchemas = {
  "agent-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/agent-event.schema.json",
  "title": "AgentEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "agent_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.agent_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "agent_id": {
      "type": "string",
      "minLength": 1
    },
    "parent_agent": {
      "type": "string"
    },
    "role": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "artifact.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/artifact.schema.json",
  "title": "Artifact",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "relative_path"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.artifact.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "relative_path": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "mime": {
      "type": "string"
    },
    "size": {
      "type": [
        "integer",
        "null"
      ],
      "minimum": 0
    },
    "sha256": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent-response.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent-response.schema.json",
  "title": "AskParentResponse",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "response_id",
    "request_id",
    "task_id",
    "text",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_response.v1"
    },
    "response_id": {
      "type": "string",
      "minLength": 1
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "text": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    }
  }
},
  "ask-parent.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/ask-parent.schema.json",
  "title": "AskParentRequest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "request_id",
    "task_id",
    "question",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.ask_parent_request.v1"
    },
    "request_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "tool_use_id": {
      "type": "string"
    },
    "parent_agent": {
      "type": "string"
    },
    "question": {
      "type": "string",
      "minLength": 1
    },
    "created_at": {
      "type": "string"
    },
    "routing": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "config.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/config.schema.json",
  "title": "ControlMeshConfig",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.config.v1"
    },
    "providers": {
      "type": "object",
      "additionalProperties": true
    },
    "api": {
      "type": "object",
      "additionalProperties": true
    },
    "messengers": {
      "type": "object",
      "additionalProperties": true
    },
    "workspace": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "doctor-result.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/doctor-result.schema.json",
  "title": "DoctorResult",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "severity",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.doctor_result.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "severity": {
      "type": "string",
      "enum": [
        "info",
        "warning",
        "error"
      ]
    },
    "message": {
      "type": "string"
    },
    "fix_hint": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "error.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/error.schema.json",
  "title": "ControlMeshError",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "code",
    "message"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.error.v1"
    },
    "code": {
      "type": "string",
      "minLength": 1
    },
    "message": {
      "type": "string"
    },
    "retryable": {
      "type": "boolean"
    },
    "correlation_id": {
      "type": "string"
    },
    "python_trace_id": {
      "type": "string"
    },
    "details": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "log-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/log-event.schema.json",
  "title": "LogEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "level",
    "source",
    "message",
    "timestamp"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.log_event.v1"
    },
    "level": {
      "type": "string",
      "enum": [
        "debug",
        "info",
        "warning",
        "error"
      ]
    },
    "source": {
      "type": "string"
    },
    "task_id": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timestamp": {
      "type": [
        "number",
        "string"
      ]
    },
    "correlation_id": {
      "type": "string"
    }
  }
},
  "memory-record.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/memory-record.schema.json",
  "title": "MemoryRecord",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "record_id",
    "source_file",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.memory_record.v1"
    },
    "record_id": {
      "type": "string",
      "minLength": 1
    },
    "source_file": {
      "type": "string",
      "minLength": 1
    },
    "section": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "promotion_state": {
      "type": "string"
    },
    "created_at": {
      "type": "string"
    },
    "metadata": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "provider-capability.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-capability.schema.json",
  "title": "ProviderCapability",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "name",
    "available",
    "health"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_capability.v1"
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "available": {
      "type": "boolean"
    },
    "version": {
      "type": "string"
    },
    "last_checked_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "health": {
      "type": "string",
      "enum": [
        "ok",
        "degraded",
        "unavailable"
      ]
    },
    "detail": {
      "type": "string"
    },
    "capabilities": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "provider-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/provider-event.schema.json",
  "title": "ProviderEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "provider",
    "kind",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.provider_event.v1"
    },
    "provider": {
      "type": "string",
      "minLength": 1
    },
    "kind": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "pid": {
      "type": [
        "integer",
        "null"
      ]
    },
    "command": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "text": {
      "type": "string"
    },
    "event_type": {
      "type": "string"
    },
    "payload": {},
    "idle_for_s": {
      "type": "number"
    },
    "elapsed_s": {
      "type": "number"
    },
    "exit_code": {
      "type": [
        "integer",
        "null"
      ]
    },
    "reason": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "timed_out": {
      "type": "boolean"
    }
  }
},
  "runtime-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/runtime-event.schema.json",
  "title": "RuntimeEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "session_key",
    "event_type",
    "created_at",
    "transport",
    "chat_id"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.runtime_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "session_key": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    }
  }
},
  "task-event.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-event.schema.json",
  "title": "TaskEvent",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "event_id",
    "task_id",
    "event_type",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task_event.v1"
    },
    "event_id": {
      "type": "string",
      "minLength": 1
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "event_type": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "created_at": {
      "type": "string"
    },
    "transport": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "topic_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "payload": {
      "type": "object",
      "additionalProperties": true
    }
  }
},
  "task-state.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task-state.schema.json",
  "title": "TaskState",
  "description": "Stable task lifecycle states exposed at the ControlMesh protocol boundary.",
  "type": "string",
  "enum": [
    "running",
    "done",
    "failed",
    "cancelled",
    "waiting",
    "detached",
    "recovering",
    "stale",
    "timeout"
  ]
},
  "task.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/task.schema.json",
  "title": "Task",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "task_id",
    "chat_id",
    "parent_agent",
    "status",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.task.v1"
    },
    "task_id": {
      "type": "string",
      "minLength": 1
    },
    "source_kind": {
      "type": "string"
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "parent_agent": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "prompt_preview": {
      "type": "string"
    },
    "provider": {
      "type": "string"
    },
    "model": {
      "type": "string"
    },
    "status": {
      "$ref": "task-state.schema.json"
    },
    "transport": {
      "type": "string"
    },
    "topology": {
      "type": "string"
    },
    "session_id": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "number",
        "string"
      ]
    },
    "completed_at": {
      "type": [
        "number",
        "string",
        "null"
      ]
    },
    "elapsed_seconds": {
      "type": "number"
    },
    "result_preview": {
      "type": "string"
    },
    "last_question": {
      "type": "string"
    }
  }
},
  "topology.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/topology.schema.json",
  "title": "Topology",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "topology_id",
    "nodes",
    "edges"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.topology.v1"
    },
    "topology_id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string"
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "id",
          "kind"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          },
          "label": {
            "type": "string"
          },
          "status": {
            "type": [
              "string",
              "null"
            ]
          },
          "role": {
            "type": [
              "string",
              "null"
            ]
          },
          "provider": {
            "type": [
              "string",
              "null"
            ]
          },
          "owner": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      }
    },
    "edges": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "required": [
          "source",
          "target",
          "kind"
        ],
        "properties": {
          "source": {
            "type": "string",
            "minLength": 1
          },
          "target": {
            "type": "string",
            "minLength": 1
          },
          "kind": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    }
  }
},
  "transport-message.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/transport-message.schema.json",
  "title": "TransportMessage",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "transport",
    "message_id",
    "chat_id",
    "created_at"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.transport_message.v1"
    },
    "transport": {
      "type": "string",
      "minLength": 1
    },
    "message_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "chat_id": {
      "type": [
        "string",
        "integer"
      ]
    },
    "thread_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "sender_id": {
      "type": [
        "string",
        "integer",
        "null"
      ]
    },
    "text": {
      "type": "string"
    },
    "command": {
      "type": "string"
    },
    "raw_payload": {},
    "created_at": {
      "type": "string"
    }
  }
},
  "workspace-manifest.schema.json": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.controlmesh.dev/controlmesh/v1/workspace-manifest.schema.json",
  "title": "WorkspaceManifest",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schema_version",
    "workspace_root",
    "paths"
  ],
  "properties": {
    "schema_version": {
      "const": "controlmesh.workspace_manifest.v1"
    },
    "workspace_root": {
      "type": "string"
    },
    "paths": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
} as const;
