import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");
const schemaDir = path.join(repoRoot, "schemas/controlmesh/v1");
const generatedDir = path.join(repoRoot, "packages/controlmesh-protocol/src/generated");
const validatorsDir = path.join(repoRoot, "packages/controlmesh-protocol/src/validators");

const header = `// Generated by packages/controlmesh-protocol/scripts/generate.mjs.\n// Do not edit manually.\n\n`;

function typeName(schema) {
  return schema.title || "UnknownSchema";
}

function literal(value) {
  return JSON.stringify(value);
}

function union(values) {
  return values.join(" | ");
}

function refToType(ref) {
  const base = path.basename(ref, ".schema.json");
  return base
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function schemaType(schema) {
  if (!schema || typeof schema !== "object") {
    return "unknown";
  }
  if (schema.const !== undefined) {
    return literal(schema.const);
  }
  if (schema.$ref) {
    return refToType(schema.$ref);
  }
  if (Array.isArray(schema.enum)) {
    return union(schema.enum.map(literal));
  }
  if (Array.isArray(schema.type)) {
    return union(schema.type.map((item) => primitiveType(item)));
  }
  if (schema.type === "array") {
    return `${schemaType(schema.items)}[]`;
  }
  if (schema.type === "object") {
    if (schema.additionalProperties && schema.additionalProperties !== true) {
      return `Record<string, ${schemaType(schema.additionalProperties)}>`;
    }
    return "Record<string, unknown>";
  }
  return primitiveType(schema.type);
}

function primitiveType(type) {
  switch (type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function renderType(schema) {
  const name = typeName(schema);
  if (schema.type !== "object") {
    return `export type ${name} = ${schemaType(schema)};\n`;
  }

  const required = new Set(schema.required || []);
  const lines = [`export interface ${name} {`];
  if (schema.additionalProperties === true) {
    lines.push("  [key: string]: unknown;");
  }
  for (const [propertyName, propertySchema] of Object.entries(schema.properties || {})) {
    const optional = required.has(propertyName) ? "" : "?";
    lines.push(`  ${JSON.stringify(propertyName)}${optional}: ${schemaType(propertySchema)};`);
  }
  lines.push("}");
  return `${lines.join("\n")}\n`;
}

const files = (await readdir(schemaDir)).filter((file) => file.endsWith(".schema.json")).sort();
const schemas = [];
for (const file of files) {
  const raw = await readFile(path.join(schemaDir, file), "utf8");
  schemas.push({ file, schema: JSON.parse(raw) });
}

const typeBody = schemas.map(({ schema }) => renderType(schema)).join("\n");
await writeFile(path.join(generatedDir, "types.ts"), `${header}${typeBody}`);

const schemaExports = schemas
  .map(({ file, schema }) => `  ${JSON.stringify(file)}: ${JSON.stringify(schema, null, 2)}`)
  .join(",\n");
await writeFile(
  path.join(validatorsDir, "schemas.ts"),
  `${header}export const controlmeshSchemas = {\n${schemaExports}\n} as const;\n`,
);
