"""Unified message envelope for all delivery paths."""

from __future__ import annotations

import enum
import hashlib
import re
import secrets
import time
from contextvars import ContextVar, Token
from dataclasses import dataclass, field
from typing import Any

from controlmesh.messenger.address import ChatRef, LockKey, TopicRef


class Origin(enum.Enum):
    """Where the message result came from."""

    BACKGROUND = "background"
    CRON = "cron"
    WEBHOOK_WAKE = "webhook_wake"
    WEBHOOK_CRON = "webhook_cron"
    HEARTBEAT = "heartbeat"
    INTERAGENT = "interagent"
    TASK_RESULT = "task_result"
    TASK_QUESTION = "task_question"
    USER = "user"
    API = "api"


class SourceScope(enum.Enum):
    """Authenticated execution-source scope inside one message origin."""

    LOCAL_FOREGROUND = "local_foreground"
    DIRECT_MESSAGE = "direct_message"
    GROUP_MESSAGE = "group_message"
    BOT_HANDOFF = "bot_handoff"
    API = "api"
    CRON = "cron"
    WEBHOOK = "webhook"
    HEARTBEAT = "heartbeat"
    BACKGROUND_TASK = "background_task"
    TASK_RESULT = "task_result"
    LEGACY_COMPAT = "legacy_compat"


_TRACE_ID_RE = re.compile(r"^[0-9a-f]{32}$")
_TRANSPORT_RE = re.compile(r"^[a-z0-9_-]{1,32}$")


@dataclass(frozen=True, slots=True)
class ExecutionContext:
    """ControlMesh-issued provenance carried to a provider process boundary.

    ``trace_id`` and ``source_ref`` are generated by trusted runtime code. Raw sender,
    prompt, credential, path, and tool-argument data are deliberately excluded.
    """

    trace_id: str
    origin: Origin
    source_scope: SourceScope
    transport: str
    source_ref: str = ""

    @classmethod
    def issue(
        cls,
        *,
        origin: Origin,
        source_scope: SourceScope,
        transport: str,
        source_id: object = "",
    ) -> ExecutionContext:
        normalized_transport = str(transport or "unknown").strip().lower()
        if not _TRANSPORT_RE.fullmatch(normalized_transport):
            normalized_transport = "unknown"
        raw_source = str(source_id or "")
        source_ref = ""
        if raw_source:
            digest_input = f"{normalized_transport}\0{raw_source}".encode()
            source_ref = hashlib.sha256(digest_input).hexdigest()[:24]
        return cls(
            trace_id=secrets.token_hex(16),
            origin=origin,
            source_scope=source_scope,
            transport=normalized_transport,
            source_ref=source_ref,
        )

    @classmethod
    def legacy(cls) -> ExecutionContext:
        """Issue an explicit host-compatible context for unclassified internal callers."""
        return cls.issue(
            origin=Origin.USER,
            source_scope=SourceScope.LEGACY_COMPAT,
            transport="legacy",
        )

    def to_dict(self) -> dict[str, str]:
        return {
            "trace_id": self.trace_id,
            "origin": self.origin.value,
            "source_scope": self.source_scope.value,
            "transport": self.transport,
            "source_ref": self.source_ref,
        }

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> ExecutionContext:
        trace_id = str(raw.get("trace_id") or "")
        transport = str(raw.get("transport") or "")
        source_ref = str(raw.get("source_ref") or "")
        if not _TRACE_ID_RE.fullmatch(trace_id):
            raise ValueError("invalid persisted execution trace_id")
        if not _TRANSPORT_RE.fullmatch(transport):
            raise ValueError("invalid persisted execution transport")
        if source_ref and not re.fullmatch(r"[0-9a-f]{24}", source_ref):
            raise ValueError("invalid persisted execution source_ref")
        return cls(
            trace_id=trace_id,
            origin=Origin(str(raw.get("origin") or "")),
            source_scope=SourceScope(str(raw.get("source_scope") or "")),
            transport=transport,
            source_ref=source_ref,
        )


_CURRENT_EXECUTION_CONTEXT: ContextVar[ExecutionContext | None] = ContextVar(
    "controlmesh_execution_context",
    default=None,
)


def current_execution_context() -> ExecutionContext | None:
    """Return provenance bound to the current async execution path, if any."""
    return _CURRENT_EXECUTION_CONTEXT.get()


def bind_execution_context(context: ExecutionContext) -> Token[ExecutionContext | None]:
    """Bind trusted provenance until ``reset_execution_context`` is called."""
    return _CURRENT_EXECUTION_CONTEXT.set(context)


def reset_execution_context(token: Token[ExecutionContext | None]) -> None:
    """Restore the prior async execution provenance."""
    _CURRENT_EXECUTION_CONTEXT.reset(token)


class DeliveryMode(enum.Enum):
    """How the result should be delivered."""

    UNICAST = "unicast"
    BROADCAST = "broadcast"


class LockMode(enum.Enum):
    """Lock acquisition strategy before delivery."""

    REQUIRED = "required"
    NONE = "none"


@dataclass(slots=True)
class Envelope:
    """Unified container for all message routing.

    Every background result, cron output, webhook response, heartbeat alert,
    inter-agent message, and task result is wrapped in an Envelope before
    being submitted to the :class:`MessageBus`.
    """

    # -- Identity --
    origin: Origin
    chat_id: ChatRef
    topic_id: TopicRef = None
    transport: str = "tg"

    # -- Input (for injection into active session) --
    prompt: str = ""
    prompt_preview: str = ""

    # -- Result (what to deliver) --
    result_text: str = ""
    delivery_text: str = ""
    output_policy: str = ""
    status: str = ""
    is_error: bool = False

    # -- Delivery configuration --
    delivery: DeliveryMode = DeliveryMode.UNICAST
    lock_mode: LockMode = LockMode.NONE
    needs_injection: bool = False

    # -- Origin-specific metadata --
    metadata: dict[str, Any] = field(default_factory=dict)

    # -- Telegram-specific --
    reply_to_message_id: int | None = None
    thread_id: int | None = None

    # -- Tracking --
    envelope_id: str = ""
    created_at: float = field(default_factory=time.time)
    elapsed_seconds: float = 0.0

    # -- Provider context --
    provider: str = ""
    model: str = ""
    session_name: str = ""
    session_id: str = ""

    # -- Trusted execution provenance (never populated from message text) --
    # Kept last to preserve the positional constructor order of the legacy envelope.
    execution_context: ExecutionContext | None = None

    @property
    def lock_key(self) -> LockKey:
        """Key for per-session lock acquisition."""
        return (self.chat_id, self.topic_id)
